
def swiftPods
    pod 'Eddystone', :git => 'https://github.com/southfox/eddystone-ios.git', :branch => 'master'
    pod 'NVActivityIndicatorView', '~> 3.1'
    pod 'SCLAlertView', '~> 0.7'
end

def tokboxPods
    pod 'OpenTok'
    pod 'OTKAnalytics'
end

target 'OpenTokBeacon' do 
    swiftPods
    tokboxPods
end

use_frameworks!
